spring.output.ansi.enabled: always
spring.mvc.favicon.enabled: false


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream

hystrix:
  timer.threadpool.default.coreSize: 1 #  //if 0 it creates threads anyway and increments them by 1
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
    ExternalServiceCall:
      circuitBreaker:
        sleepWindowInMilliseconds: 5000